<?php if(Mage::registry('current_category') ):?>
<?php
    $categories = Mage::getModel('catalog/category')->load(Mage::registry('current_category')->getID())->getChildren();
    if (!empty($categories)):
        $categoryIDs = explode(',',$categories);
        ?>
    <nav role="navigation" id="bottomMenu" style="" class="show-for-small columns twelve">
        <ul class="nav-bar" id="bottomNav">
            <?php foreach($categoryIDs as $categoryID): ?>
            <li>
                <?php $category = Mage::getModel('catalog/category')->load($categoryID);?>
                <a href="<?php echo $category->getUrl()?>">
                    <?php echo $category->getName()?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </nav>
    <?php endif; ?>
<?php else: ?>
<nav role="navigation" id="bottomMenu" style="" class="show-for-small columns twelve">
    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>
    <?php if (count($_categories) > 0): ?>
    <ul class="nav-bar" id="bottomNav">
        <?php foreach($_categories as $_category): ?>
        <li>
            <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                <?php echo $_category->getName() ?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</nav>
<?php endif; ?>

<script type="text/javascript" >

    ;(function (window, document, $) {
        // Set the negative margin on the top menu for slide-menu pages
        var $selector1 = $('#topMenu'),
                events = 'click.fndtn';
        if ($selector1.length > 0) $selector1.css("margin-top", $selector1.height() * -1);

        // Watch for clicks to show the sidebar
        var $selector2 = $('#sidebarButton');
        if ($selector2.length > 0) {
            $('#sidebarButton').on(events, function (e) {
                e.preventDefault();
                $('body').toggleClass('active');
            });
        }

        // Watch for clicks to show the menu for slide-menu pages
        var $selector3 = $('#menuButton');
        if ($selector3.length > 0) {
            $('#menuButton').on(events, function (e) {
                //e.preventDefault();
                $('body').toggleClass('active-menu');
            });
        }

        // // Adjust sidebars and sizes when resized
        // $(window).resize(function() {
        // // if (!navigator.userAgent.match(/Android/i)) $('body').removeClass('active');
        // var $selector4 = $('#topMenu');
        // if ($selector4.length > 0) $selector4.css("margin-top", $selector4.height() * -1);
        // });

        // Switch panels for the paneled nav on mobile
        var $selector5 = $('#switchPanels');
        if ($selector5.length > 0) {
            $('#switchPanels dd').on(events, function (e) {
                e.preventDefault();
                var switchToPanel = $(this).children('a').attr('href'),
                        switchToIndex = $(switchToPanel).index();
                $(this).toggleClass('active').siblings().removeClass('active');
                $(switchToPanel).parent().css("left", (switchToIndex * (-100) + '%'));
            });
        }

        $('#nav-zurb li a').on(events, function (e) {
            e.preventDefault();
            var href = $(this).attr('href'),
                    $target = $(href);
            $('html, body').animate({scrollTop : $target.offset().top}, 300);
        });
    }(this, document, jQuery.noConflict()));

</script>