<?php if (Mage::registry('current_category')): ?>
<?php   $categories = Mage::getModel('catalog/category')->load(Mage::registry('current_category')->getID())->getChildren(); ?>
<?php endif; ?>

<nav role="navigation" id="bottomMenu" style="" class="show-for-small columns twelve">
    <ul class="nav-bar" id="bottomNav">

<?php if (isset($categories) && !empty($categories) ) :?>
<?php       $categoryIDs = explode(',',$categories);    ?>
            <?php foreach($categoryIDs as $categoryID): ?>
            <li>
                <?php $category = Mage::getModel('catalog/category')->load($categoryID);?>
                <a href="<?php echo $category->getUrl()?>">
                    <?php echo $category->getName()?>
                </a>
            </li>
            <?php endforeach; ?>
<?php else: ?>
            <?php $_helper = Mage::helper('catalog/category') ?>
            <?php $_categories = $_helper->getStoreCategories() ?>
            <?php if (count($_categories) > 0): ?>
                <?php foreach($_categories as $_category): ?>
                <li>
                    <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                        <?php echo $_category->getName() ?>
                    </a>
                </li>
                <?php endforeach; ?>
            <?php endif; ?>
<?php endif; ?>
    </ul>
</nav>
