
<div class="home-content columns large-12">
    <span data-tooltip class="has-tip" title="Tooltips are awesome, you should totally use them!">extended information</span>

    <a href="#" data-dropdown="drop1">Has Dropdown</a>
    <a href="#" data-dropdown="drop2">Has Content Dropdown</a>

    <ul id="drop1" class="f-dropdown" data-dropdown-content>
      <li><a href="#">This is a link</a></li>
      <li><a href="#">This is another</a></li>
      <li><a href="#">Yet another</a></li>
    </ul>

    <ul id="drop2" class="f-dropdown content" data-dropdown-content>
      <li><a href="#">This is a link</a></li>
      <li><a href="#">This is another</a></li>
      <li><a href="#">Yet another</a></li>
    </ul>


    <div id="myModal" class="reveal-modal">
      <h2>Awesome. I have it.</h2>
      <p class="lead">Your couch.  It is mine.</p>
      <p>Im a cool paragraph that lives inside of an even cooler modal. Wins</p>
      <a class="close-reveal-modal">&#215;</a>
    </div>
    <div class="section-container auto" data-section>
      <section>
        <p class="title" data-section-title><a href="#panel1">Section 1</a></p>
        <div class="content" data-section-content>
          <p>Content of section 1.</p>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel2">Section 2</a></p>
        <div class="content" data-section-content>
          <p>Content of section 2.</p>
        </div>
      </section>
    </div>

    <div class="section-auto-sample-accordion" data-section="accordion" style="">
          <section style="" class="active">
            <p class="title-sample" data-section-title="" ><a href="#section1">Section 1</a></p>
            <div class="content-sample" data-slug="section1" data-section-content="" style="">
              <p>Content of section 1.</p>
            </div>
          </section>
          <section>
            <p class="title-sample" data-section-title="" ><a href="#section1">Section 2</a></p>
            <div class="content-sample" data-slug="section2" data-section-content="" style="">
              <p>Content of section 2.</p>
            </div>
          </section>
    </div>


    <div class="section-container auto" data-section data-options="rtl: true">
      <section>
        <p class="title" data-section-title><a href="#panel1">Section 1</a></p>
        <div class="content" data-section-content>
          <p>Content of section 1.</p>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel2">Section 2</a></p>
        <div class="content" data-section-content>
          <p>Content of section 2.</p>
        </div>
      </section>
    </div>

    <div class="section-container vertical-tabs" data-section="vertical-tabs">
      <section>
        <p class="title" data-section-title><a href="#">Section 1</a></p>
        <div class="content" data-section-content>
          <p>Content of section 1.</p>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#">Section 2</a></p>
        <div class="content" data-section-content>
          <p>Content of section 2.</p>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#">Section 3</a></p>
        <div class="content" data-section-content>
          <p>Content of section 3.</p>
        </div>
      </section>
    </div>

    <a href="#" data-dropdown="drop" class="tiny button dropdown">Dropdown Button</a><br>
    <a href="#" data-dropdown="drop2" class="small secondary radius button dropdown">Dropdown Button</a><br>
    <a href="#" data-dropdown="drop3" class="button alert round dropdown">Dropdown Button</a><br>
    <a href="#" data-dropdown="drop4" class="large success button dropdown">Dropdown Button</a><br>
    <a href="#" data-dropdown="drop5" class="large button dropdown expand">Dropdown Button</a><br>

    <ul id="drop" data-dropdown-content="" class="f-dropdown">
      <li><a href="#">This is a link</a></li>
      <li><a href="#">This is another</a></li>
      <li><a href="#">Yet another</a></li>
    </ul>
    <ul id="drop2" data-dropdown-content="" class="f-dropdown">
      <li><a href="#">This is a link</a></li>
      <li><a href="#">This is another</a></li>
      <li><a href="#">Yet another</a></li>
    </ul>
    <ul id="drop3" data-dropdown-content="" class="f-dropdown">
      <li><a href="#">This is a link</a></li>
      <li><a href="#">This is another</a></li>
      <li><a href="#">Yet another</a></li>
    </ul>

</div>
