<div class="super-header">
    <div class="super-header-content row">
        <div class="welcome-msg columns large-6">
            <p><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>

        </div>
        <div class="store-currency columns large-2">
            <?php echo $this->getChildHtml('store_currency_selector') ?>
        </div>
        <div class="site-language columns large-3">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>
    </div>
</div>

<header class="site-header">
    <div class="site-header-content row">
        <div class="site-identity columns large-4">
        <?php if ($this->getIsHomePage()):?>
            <h1 class="site-logo">
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="site-logo">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </a>
            </h1>
        <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        </div>

        <div class="site-search columns large-4">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

        <div class="site-cart columns large-3">
            <i class="icon-shopping-cart"></i>
                <?php
                $count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
                $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
                ?>

                <?php if($count == 0):?>
                    <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('0 Items', $count) ?></a>
                <?php endif; ?>
                <?php if($count == 1):?>
                    <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('1 Item', $count) ?></a>
                <?php endif; ?>
                <?php if($count >= 2):?>
                    <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('%s Items', $count) ?></a>
                <?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?>
                <a class="cartgo" href="<?php echo $this->getUrl('checkout') ?>"><?php echo $this->__('Checkout') ?></a>

        </div>

        <div class="site-account columns large-1">
            <nav class="top-bar">
                <ul class="title-area">
                    <li class="name"></li>
                    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
                </ul>
                <section class="top-bar-section">
                    <ul class="right">
                        <li class="has-dropdown"><a href="#"><i class="icon-user"></i></a>
                            <ul class="dropdown">
                                <li class="">
                                    <?php if($this->helper('customer')->isLoggedIn()): ?>
                                        <a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log out') ?></a>
                                    <?php else: ?>
                                        <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Log in') ?></a>
                                    <?php endif; ?>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </section>
            </nav>

        </div>

    </div>
</header>
<div class="site-nav row">
        <div class="columns large-12">
            <nav class="top-bar">
                <ul class="title-area">
                    <li class="name"></li>
                    <li class="toggle-topbar menu-icon"><a href="#"><span><?php echo $this->__('Menu') ?></span></a></li>
                </ul>
                <section class="top-bar-section">

                    <ul class="left">
                        <?php echo $this->getChildHtml('topMenu') ?>
                    </ul>
                </section>
            </nav>
        </div>
</div>

