<header class="row">
    <div class="columns two">
    <?php if ($this->getIsHomePage()):?>
        <h1 class="logo">
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
            </a>
        </h1>
    <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
    <?php endif?>
    </div>
    <div class="columns ten">
        <div class="row">
        <div class="columns four">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

            <div class="columns three">



                <?php
                $count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
                $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
                ?>
                <?php if($count == 0):?>
                    <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('0 Items', $count) ?></a>
                <?php endif; ?>
                <?php if($count == 1):?>
                    <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('1 Item', $count) ?></a>
                <?php endif; ?>
                <?php if($count >= 2):?>
                    <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('%s Items', $count) ?></a>
                <?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?>
                <a class="cartgo" href="<?php echo $this->getUrl('checkout') ?>"><?php echo $this->__('Checkout') ?></a>

            </div>
            <div class="columns three">
                <ul class="nav-bar">
                    <li class="has-flyout">
                        <a href="<?php echo $this->getUrl('customer/account') ?>">My account</a>
                        <a href="#" class="flyout-toggle"><span> </span></a>
                        <ul class="flyout">
                            <li>
                                <?php if($this->helper('customer')->isLoggedIn()):   ?>
                                    <a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log out') ?></a>
                                <?php else: ?>
                                    <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Log in') ?></a>
                                <?php endif; ?>
                            </li>

                        </ul>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</header>
<div class="row">
    <div class="columns twelve">
    <nav class="top-bar">
        <ul>
            <li class="name">

            </li>
            <li class="toggle-topbar"><a href="#"></a></li>
        </ul>
        <section>
            <ul class="left">
        <?php echo $this->getChildHtml('topMenu') ?>
            </ul>
        </section>
    </nav>
    </div>
</div>

