<div class="super-header">
    <div class="super-header-content row">
        <div class="welcome-msg columns large-2">
            <p><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
        </div>
        <div class="columns large-10 site-utilities">

                <div class="switchers columns large-9">
                    <div class="row">
                    <?php echo $this->getChildHtml('store_switcher') ?>
                    <?php echo $this->getChildHtml('store_currency_selector') ?>
                    <?php echo $this->getChildHtml('store_language') ?>
                    </div>
                </div>

                 <?php echo $this->getChildHtml('top_cart') ?>


            <div class="site-account columns large-2 small-4">
                <?php echo $this->getChildHtml('mini_account') ?>
            </div>
        </div>
    </div>
</div>

<header class="site-header">
    <div class="site-header-content row">
        <div class="site-identity columns large-2 small-12">
        <?php if ($this->getIsHomePage()):?>
            <h1 class="site-logo">
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="site-logo">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </a>
            </h1>
        <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        </div>

        <div class="site-search columns large-10 small-12">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>



    </div>
</header>
<div class="site-nav row">
        <div class="columns large-12">
            <nav class="top-bar" data-topbar>
                <ul class="title-area">
                    <li class="name"></li>
                    <li class="toggle-topbar menu-icon"><a href="#"><span><?php echo $this->__('Menu') ?></span></a></li>
                </ul>
                <section class="top-bar-section">

                    <ul class="left">
                        <?php echo $this->getChildHtml('topMenu') ?>
                    </ul>
                </section>
            </nav>
        </div>
</div>

