<?php /* Initializes all functions appropriately when using all functions inside foundation.min.js */ ?>
<!--<script src="<?php /*echo $this->getSkinUrl('bower_components/foundation/js/foundation.js') */?>"></script>-->
<!--<script src="<?php /*echo $this->getSkinUrl('bower_components/foundation/js/foundation.min.js') */?>"></script>-->
<script src="<?php echo $this->getSkinUrl('js/app.js') ?>"></script>


<!--
  * From now on, JS is loaded separately by components in local.xml. Use only what you need! If you want from some reason full foundation, comment components and uncomment foundation.js here in js.phtml.
  --> 


