<div class="mini-acc">
<nav class="mini-account">
    <?php if($this->helper('customer')->isLoggedIn()): ?>
        <a href="#" data-dropdown="accmini" class="acc-button">My account</a>
           <ul id="accmini" data-dropdown-content class="f-dropdown">
               <li><a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('Dashboard') ?></a></li>
               <li><a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log out') ?></a></li>
           </ul>
    <?php else: ?>
        <a class="acc-button" href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('My Account') ?></a>
    <?php endif; ?>
</nav>
</div>

